server:
  port: 8080

base:
  url: http://localhost:8080

spring:
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: "your email address"
    password: "your password"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/fur_guard
    password: "your password"
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update

---

spring:
  config:
    activate:
      on-profile: qa
  datasource:
    url: jdbc:mysql://localhost:3306/qa_db
    username: root
    password: Lakindu@MySQL
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/prod_db
    username: root
    password: Lakindu@MySQL
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true